print("hello world")
print("i feel so alone on a friday night")
print("if you go i'd stay, you come back ill be right here")
print("salvatore can wait now its time to eat soft icecream")
print("luan nn tem senso")
print("if i could figure out id take you back to my house so we can meddle about")
print("break up, make up, total waste of time")
print("im afraid of changes")
print("healing energy on me")
print("save your advices cuz i wont hear, you may be right but idc")
